### PR TITLE
add new plan url for building

### PR DESCRIPTION
**Pull request by paresy**

### CODE REVIEW

**Comment by mkiehl** [comment]
Vorschlag für Attributname: floorPlanPDF

**Comment by Siedlerchr** [comment]
I would go with floorPlan. Can we ensure that always a pdf is used?

**Comment by paresy** [comment]
Sure, i can validate the file extension and if required also the contents (at least with some heuristic)

I would prefer floorPlan as well. If we need to add support for images we could do this quite easily.

**Comment by paresy** [comment]
I pushed the change to rename the field to floorPlan

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
